### ISSUE TITLE
hello help,there is a error!

### ISSUE THREAD

**Issue by aisangsangshu** [Pi4J/pi4j-example-fatjar#1]
![image](https://user-images.githubusercontent.com/12061611/208073228-4c11a7bf-0233-43ef-b700-b8e5a5ff2151.png)
hello,compile with raspberry 4b,there is a error!
![image](https://user-images.githubusercontent.com/12061611/208073398-e915c9b0-554f-4f7a-8bd8-a4fc61e45a86.png)
compile with raspberry zerow,there is a error!

**Comment by FDelporte** [comment]
are you running with sudo?

**Comment by aisangsangshu** [comment]
> are you running with sudo?
thanks!I am careless and lost it!

**Comment by FDelporte** [comment]
No problem, happy we quickly found the solution :-)
